package com.dl2.fyp.enums;

public enum SectorCategory {
  COMMUNICATION_SERVICES,
  CONSUMER_DISCRETIONARY,
  CONSUMER_STAPLES,
  ENERGY,
  FINANCIALS,
  HEALTH_CARE,
  INDUSTRIALS,
  INFORMATION_TECHNOLOGY,
  MATERIALS,
  REAL_ESTATE,
  UTILITIES
}
